version: '3'

services:        
    mysqldb:
        image: mysql:5.7
        container_name : my-mysql        
        restart : always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - ./mysql-data:/var/lib/mysql  
        networks:
            - my-admin-network
    myadmin:
        image: phpmyadmin/phpmyadmin:5.0
        container_name : my-admin
        restart : always
        ports:
            - "8081:80"     
        environment:
            PMA_HOST: mysqldb
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        networks:
              - my-admin-network      
networks:
    my-admin-network:
        driver: bridge            
            